/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.UsuariosData;
import entidades.Usuarios;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class GestionUsuarios extends javax.swing.JInternalFrame {

    private UsuariosData userD = new UsuariosData();
    private Usuarios user = null;
    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        initComponents();
        armarCabecera();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfSexo = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfCargo = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfContraseña = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnRecepcionistas = new javax.swing.JButton();
        btnAdministradores = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(2117483647, 2147483647));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DNI");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sexo");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Direccion");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cargo");

        btnModificar.setText("Nuevo");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña");

        btnRefresh.setText("<=");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombre)
                    .addComponent(tfApellido)
                    .addComponent(tfDni)
                    .addComponent(tfSexo)
                    .addComponent(tfDireccion)
                    .addComponent(tfCargo)
                    .addComponent(tfContraseña))
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnModificar)
                .addGap(49, 49, 49)
                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(btnCrear)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCrear)
                    .addComponent(btnRefresh))
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRecepcionistas.setText("Seleccionar los recepcionistas");
        btnRecepcionistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionistasActionPerformed(evt);
            }
        });

        btnAdministradores.setText("Seleccionar los administradores");
        btnAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradoresActionPerformed(evt);
            }
        });

        btnDefault.setText("<=");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnRecepcionistas)
                .addGap(29, 29, 29)
                .addComponent(btnDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnAdministradores)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(247, 247, 247))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecepcionistas)
                    .addComponent(btnDefault)
                    .addComponent(btnAdministradores))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnEliminar)
                .addGap(68, 68, 68))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Registro de usuario");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Listado de usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        String nombre = tfNombre.getText();
        String ape = tfApellido.getText();
        int dni = Integer.parseInt(tfDni.getText());
        String sexo = tfSexo.getText();
        String dir = tfDireccion.getText();
        String cargo = tfCargo.getText();
        String contra = tfContraseña.getText();
        
        if (tfNombre.getText().isEmpty() || tfApellido.getText().isEmpty() || tfDni.getText().isEmpty()
                || tfSexo.getText().isEmpty() || tfDireccion.getText().isEmpty() || tfCargo.getText().isEmpty()
                || tfContraseña.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Hay campos vacios");
            limpiarCampos();
            return;
        }

        try {
            int filaSeleccionada = jTable1.getSelectedRow();// traigo la fila seleccionada

            if (filaSeleccionada != -1) {

                Usuarios usuariomodificado = userD.obtenerUsuarioPorDni(dni);
                if (usuariomodificado != null) {
                    usuariomodificado.setNombre(nombre);
                    usuariomodificado.setApellido(ape);
                    usuariomodificado.setDni(dni);
                    usuariomodificado.setSexo(sexo);
                    usuariomodificado.setDireccion(dir);
                    usuariomodificado.setCargo(cargo);
                    usuariomodificado.setContraseña(contra);
                    userD.modificarUsuario(usuariomodificado);
                    limpiarCampos();
                }
            } else {
                user.setNombre(nombre);
                user.setApellido(ape);
                user.setDni(dni);
                user.setSexo(sexo);
                user.setDireccion(dir);
                user.setCargo(cargo);
                user.setContraseña(contra);
                
                userD.modificarEstadoUsuario(dni);

                 //userD.modificarEstadoHuesped(dni);
                 btnModificar.setEnabled(true);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar numeros para guardar su contacto");

        }
        limpiarCampos();
        limpiarTabla();
        llenarTabla();
    
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        String nombre = tfNombre.getText();
        String ape = tfApellido.getText();
        int dni = Integer.parseInt(tfDni.getText());
        String sexo = tfSexo.getText();
        String dir = tfDireccion.getText();
        String cargo = tfCargo.getText();
        String contra = tfContraseña.getText();
        
        if (tfNombre.getText().isEmpty() || tfApellido.getText().isEmpty() || tfDni.getText().isEmpty()
                || tfSexo.getText().isEmpty() || tfDireccion.getText().isEmpty() || tfCargo.getText().isEmpty()
                || tfContraseña.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Hay campos vacios");
            limpiarCampos();
            return;
        }

        try {

            user = userD.obtenerUsuarioPorDni(dni);

            if (user != null) {
                btnCrear.setEnabled(false);
                JOptionPane.showMessageDialog(null,
                        "El numero de documento ingresado ya se encuentra en la base de datos,"
                        + " Por favor revise la información y presione modificar para reestablecer los datos ", "Dni encontrado", JOptionPane.INFORMATION_MESSAGE);

                tfNombre.setText(user.getNombre());
                tfApellido.setText(user.getApellido());
                tfDni.setText(Integer.toString(user.getDni()));
                tfSexo.setText(user.getSexo());
                tfDireccion.setText(user.getDireccion());
                tfCargo.setText(user.getCargo());
                tfContraseña.setText(user.getContraseña());
            }

            if (user == null) {
                user = new Usuarios(nombre, ape, dni, sexo, dir, cargo, true, contra);
                userD.crearUsuario(user);

                limpiarCampos();

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar numeros para guardar su contacto");
        }

        /*huesped = hData.buscarHuespedPorDni(numeroDocumento);

        if (huesped != null) {
            jBGuardar.setEnabled(false);
            JOptionPane.showMessageDialog(null,
                    "El numero de documento ingresado ya se encuentra en la base de datos,"
                    + " Por favor revise la información y presione modificar para reestablecer los datos ", "Dni encontrado", JOptionPane.INFORMATION_MESSAGE);

            jTNombre.setText(huesped.getNombre());
            jTApellido.setText(huesped.getApellido());
            jCTipoDocumento.setSelectedItem(huesped.getTipoDocumento());
            jTNumeroDocumento.setText(huesped.getNumeroDocumento());
            jTDomicilio.setText(huesped.getDomicilio());
            jTCorreo.setText(huesped.getCorreo());
            jTTelefono.setText(String.valueOf(huesped.getCelular()));
            jBModificar.setEnabled(true);
        }

        JOptionPane.showMessageDialog(null, "Llena los campos y crea");
        rbEstado.setSelected(true);
        tfBuscarDni.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModificar.setEnabled(false);
        try {
            if (tfNombre.getText().isEmpty() || tfApellido.getText().isEmpty() || tfDni.getText().isEmpty()
                    || tfSexo.getText().isEmpty() || tfDireccion.getText().isEmpty() || tfCargo.getText().isEmpty()
                    || tfContraseña.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Hay campos vacios");
                limpiarCampos();
                return;
            }

            String nombre = tfNombre.getText();
            String ape = tfApellido.getText();
            int dni = Integer.parseInt(tfDni.getText());
            String sexo = tfSexo.getText();
            String dir = tfDireccion.getText();
            String cargo = tfCargo.getText();
            String contra = tfContraseña.getText();
            boolean est = rbEstado.isSelected();

            UsuariosData userD = new UsuariosData();
            Usuarios user = new Usuarios();
            user.setNombre(nombre);
            user.setApellido(ape);
            user.setDni(dni);
            user.setSexo(sexo);
            user.setDireccion(dir);
            user.setCargo(cargo);
            user.setContraseña(contra);
            user.setEstado(est);

            userD.crearUsuario(user);
            limpiarCampos();
            tfBuscarDni.setEnabled(true);
            btnBuscar.setEnabled(true);
            btnModificar.setEnabled(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingresa valores válidos");
            limpiarCampos();
        }*/
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRecepcionistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionistasActionPerformed

        limpiarTabla(); // limpio la tabla para que no se agreguen abajo de la default
        UsuariosData ud = new UsuariosData();
        for (Usuarios user : ud.ListarRecepcionistas()) { //cargo con el metodo
            cargarTabla(user);
        }

    }//GEN-LAST:event_btnRecepcionistasActionPerformed

    private void btnAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradoresActionPerformed

        limpiarTabla(); // limpio la tabla para que no se agreguen abajo de la default
        UsuariosData ud = new UsuariosData();
        for (Usuarios user : ud.ListarAdninistradores()) { //cargo con el metodo
            cargarTabla(user);
        }

    }//GEN-LAST:event_btnAdministradoresActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed

        limpiarTabla();
        llenarTabla();

    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        UsuariosData userD = new UsuariosData();
        int respuesta = JOptionPane.showConfirmDialog(null,
                "Desea eliminar este usuario", "Eliminar Usuario", JOptionPane.OK_OPTION);
        int filaSeleccionada = jTable1.getSelectedRow();

        if (respuesta == 0 && filaSeleccionada != -1) {
            int dni = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 2).toString());
            userD.eliminarUsuarioPorDni(dni);
            limpiarCampos();
            limpiarTabla();
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Debes Seleccionar el huesped para eliminar");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        btnModificar.setEnabled(true);
        btnCrear.setEnabled(true);
        limpiarCampos();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        activarCampos(true);
        int filaSeleccionada = jTable1.getSelectedRow();// traigo la fila seleccionada

        if (filaSeleccionada != -1) {//nos aseguramos que haya una fila seleccionada
            String nombre = (String) jTable1.getValueAt(filaSeleccionada, 0);
            String apellido = (String) jTable1.getValueAt(filaSeleccionada, 1);
            int dni = (Integer) jTable1.getValueAt(filaSeleccionada, 2);
            String sexo = (String) jTable1.getValueAt(filaSeleccionada, 3);
            String domicilio = (String) jTable1.getValueAt(filaSeleccionada, 4);
            String cargo = (String) jTable1.getValueAt(filaSeleccionada, 5);
            String contra = jTable1.getValueAt(filaSeleccionada, 7).toString();

            tfNombre.setText(nombre);
            tfApellido.setText(apellido);
            tfDni.setText(Integer.toString(dni));
            tfSexo.setText(sexo);
            tfDireccion.setText(domicilio);
            tfCargo.setText(cargo);
            tfContraseña.setText(contra);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void limpiarTabla() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministradores;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRecepcionistas;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCargo;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSexo;
    // End of variables declaration//GEN-END:variables

    public void activarCampos(boolean a) {
        tfNombre.setEditable(a);
        tfApellido.setEditable(a);
        tfDni.setEditable(a);
        tfSexo.setEditable(a);
        tfDireccion.setEditable(a);
        tfCargo.setEditable(a);
    }

    public void enabled(boolean a) {
        tfNombre.setEnabled(a);
        tfApellido.setEnabled(a);
        tfDni.setEnabled(a);
        tfSexo.setEnabled(a);
        tfDireccion.setEnabled(a);
        tfCargo.setEnabled(a);
    }

    public void limpiarCampos() {
        tfNombre.setText("");
        tfApellido.setText("");
        tfDni.setText("");
        tfSexo.setText("");
        tfDireccion.setText("");
        tfCargo.setText("");
        tfContraseña.setText("");;
    }

    private void armarCabecera() {
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Sexo");
        modelo.addColumn("Direccion");
        modelo.addColumn("Cargo");
        modelo.addColumn("estado");
        modelo.addColumn("contraseña");
        jTable1.setModel(modelo);
    }

    private void cargarTabla(Usuarios users) {
        modelo.addRow(new Object[]{
            users.getNombre(),
            users.getApellido(),
            users.getDni(),
            users.getSexo(),
            users.getDireccion(),
            users.getCargo(),
            users.isEstado(),
            users.getContraseña()
        });
    }

    private void llenarTabla() {
        UsuariosData ud = new UsuariosData();
        for (Usuarios user : ud.listarUsuarios()) {
            cargarTabla(user);
        }
    }

}
