/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.PagosData;
import accesoADatos.ReservaData;
import entidades.Pagos;
import entidades.Reserva;
import java.awt.print.*;
import java.awt.*;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernandoalvarez
 */
public class ImprimirFacturasORecibos extends javax.swing.JInternalFrame implements Printable {

    public PagosData pagos = new PagosData();
    public ReservaData res = new ReservaData();
    public Reserva a = res.buscarReservaId(idReserva);
    public static int idReserva = PagosView.idReserva;
    public String idPago;
    LocalDate hoy = LocalDate.now();
    
 private DefaultTableModel modeloTablaPagos = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    /**
     * Creates new form ImprimirFacturasORecibos
     */
    public ImprimirFacturasORecibos(String x) {
        this.idPago = x;
        initComponents();
       
        Pagos p = pagos.buscarPagoPorId(Integer.parseInt(idPago));
        armarCabeceraListaPagos();
        cargarTablaPagos(p);
        jLabelCategoria.setText(p.getTipoComprobante());
        String nombres = a.getIdHuesped().getNombre()+", "+a.getIdHuesped().getApellido();
        jTextNombreCliente.setText(nombres);
        String fechaDelDia = hoy.toString();
        jLabelFecha.setText(fechaDelDia);
        jLTotal.setText("Consumo Total: "+p.getImporteTotal() );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFactura = new javax.swing.JPanel();
        jLabelCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFactura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextNombreCliente = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBimprimir = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(405, 427));
        setSize(new java.awt.Dimension(405, 427));
        getContentPane().setLayout(null);

        jPFactura.setBackground(new java.awt.Color(255, 255, 255));
        jPFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPFactura.setPreferredSize(new java.awt.Dimension(405, 380));
        jPFactura.setSize(new java.awt.Dimension(410, 380));

        jLabelCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTableFactura.setBackground(new java.awt.Color(255, 255, 255));
        jTableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFactura);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cliente : ");

        jTextNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        jTextNombreCliente.setBorder(null);

        jLTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de emisión ");

        javax.swing.GroupLayout jPFacturaLayout = new javax.swing.GroupLayout(jPFactura);
        jPFactura.setLayout(jPFacturaLayout);
        jPFacturaLayout.setHorizontalGroup(
            jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFacturaLayout.createSequentialGroup()
                .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPFacturaLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPFacturaLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPFacturaLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPFacturaLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPFacturaLayout.setVerticalGroup(
            jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFacturaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFacturaLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(jPFacturaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPFactura);
        jPFactura.setBounds(0, -20, 410, 380);

        jBimprimir.setBackground(new java.awt.Color(95, 0, 0));
        jBimprimir.setForeground(new java.awt.Color(255, 255, 255));
        jBimprimir.setText("Imprimir");
        jBimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jBimprimir);
        jBimprimir.setBounds(150, 360, 84, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirActionPerformed
        try{
            PrinterJob gap = PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top = gap.printDialog();
            if (top){
                gap.print();
            }
        }catch(PrinterException ex){

            JOptionPane.showMessageDialog(null, "Error en la impresión");
        }
    }//GEN-LAST:event_jBimprimirActionPerformed

   private void armarCabeceraListaPagos() {
        modeloTablaPagos.addColumn("Id");//0
        modeloTablaPagos.addColumn("Fecha de emision");//1
        modeloTablaPagos.addColumn("Forma de Pago");//2
        modeloTablaPagos.addColumn("Medio de Pago");//3    
        modeloTablaPagos.addColumn("Importe Total");//4
        modeloTablaPagos.addColumn("Tipo de Comprobante");//5
       
        jTableFactura.setModel(modeloTablaPagos);
    }
   
   private void cargarTablaPagos(Pagos p) {
        modeloTablaPagos.addRow(new Object[]{
            p.getIdPagos(),
            p.getFechaEmision(),
            p.getFormaDePago(),
            p.getMedioPago(),
             p.getImporteTotal(),
            p.getTipoComprobante()
           
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBimprimir;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFactura;
    private javax.swing.JTextField jTextNombreCliente;
    // End of variables declaration//GEN-END:variables
  @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        
        if (index > 0){
            
            return NO_SUCH_PAGE;
            
        }
        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagfor.getImageableX()+ 30 ,pagfor.getImageableY() + 30);
        hub.scale(1.0, 1.0);
        jPFactura.printAll(graf);
        return PAGE_EXISTS;
        
    }

}
