/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ReservaData;
import accesoADatos.UsuariosData;
import entidades.Huesped;
import entidades.Reserva;
import entidades.Usuarios;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.table.DefaultTableModel;
import static vistas.VistaReserva.jDCfechaEntrada;
import static vistas.VistaReserva.jDCfechaSalida;
import static vistas.VistaReserva.jTAdmin;
import static vistas.VistaReserva.jTCantPersonas;
import static vistas.VistaReserva.jTHabitacion;
import static vistas.VistaReserva.jTHusped;
import static vistas.VistaReserva.jTImporte;
import static vistas.VistaReserva.jTablareservas;

/**
 *
 * @author 54911
 */
public class ListaReservas extends javax.swing.JInternalFrame {
public ReservaData resd= new ReservaData();
public Huesped h= new Huesped();
public UsuariosData user= new UsuariosData();
Usuarios usuario;
LocalDate fecha1 ,fecha2;
private DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    /**
     * Creates new form ListaReservas
     */
    public ListaReservas() {
        initComponents();
        armarCabecera();
//        llenarTabla();
        listaRegistros();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTReservas = new javax.swing.JTable();
        jTnroRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1050, 534));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(151, 60, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(941, 551));

        jTextbuscar.setBackground(new java.awt.Color(153, 51, 0));
        jTextbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTextbuscar.setText("Busca por nombre");
        jTextbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextbuscarFocusLost(evt);
            }
        });
        jTextbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextbuscarKeyReleased(evt);
            }
        });

        jTReservas.setBackground(new java.awt.Color(153, 51, 0));
        jTReservas.setForeground(new java.awt.Color(255, 255, 255));
        jTReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTReservas.setPreferredSize(new java.awt.Dimension(700, 250));
        jTReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTReservas);

        jTnroRegistro.setBackground(new java.awt.Color(153, 51, 0));
        jTnroRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jTnroRegistro.setText("Total de registros:");
        jTnroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnroRegistroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Reservas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 803, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTnroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jTnroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextbuscarFocusGained
        jTextbuscar.setText("");
    }//GEN-LAST:event_jTextbuscarFocusGained

    private void jTextbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextbuscarFocusLost
        jTextbuscar.setText("Busca por numero de documento");
    }//GEN-LAST:event_jTextbuscarFocusLost

    private void jTextbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextbuscarKeyReleased
        borrarFilas();
        for (Reserva res : resd.listarReserva()) {

        if(res.getIdHuesped().getNumeroDocumento().startsWith(jTextbuscar.getText())){
            modeloTabla.addRow(new Object[]{
            res.getIdReserva(),
            res.getIdHabitacion().getNumHabitacion(),
            res.getIdHabitacion().getPiso(),
            res.getIdHabitacion().isEstado(),
            res.getIdHuesped().getNombre(),
            res.getIdHuesped().getApellido(),
            res.getIdHuesped().getTipoDocumento(),
            res.getIdHuesped().getNumeroDocumento(),
            res.getIdHabitacion().getIdTipoHabitacion().getCategoria(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantCamas(),
            res.getIdHabitacion().getIdTipoHabitacion().getTipoCama(),
            res.getIdHabitacion().getIdTipoHabitacion().getPrecio(),
            res.getFechaEntrada(),
            res.getFechaSalida(),
            res.getImporteTotal(),
            res.getIdUsuarios().getIdUsuario(),
                });
    }
            
        }   
    }//GEN-LAST:event_jTextbuscarKeyReleased
  

    private void jTReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTReservasMouseClicked
    }//GEN-LAST:event_jTReservasMouseClicked

    private void jTnroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnroRegistroActionPerformed
        
    }//GEN-LAST:event_jTnroRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTReservas;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTextField jTnroRegistro;
    // End of variables declaration//GEN-END:variables

 private void armarCabecera() {
        modeloTabla.addColumn("IdReserva");//0
        modeloTabla.addColumn("NºHabitación ");//1
        modeloTabla.addColumn("Piso");//2
        modeloTabla.addColumn("Estado");//3
        modeloTabla.addColumn("Nombre Huesped");//4
        modeloTabla.addColumn("Apellido Huesped");//5
        modeloTabla.addColumn("Tipo de Documento");//6
        modeloTabla.addColumn("Numero de Documento");//7
        modeloTabla.addColumn("Categoría");//8
        modeloTabla.addColumn("Cant.Personas");//9
        modeloTabla.addColumn("Cant.Camas");//10
        modeloTabla.addColumn("Tipo de Camas");//11
        modeloTabla.addColumn("Precio");//12
        modeloTabla.addColumn("Fecha entrada");//13
        modeloTabla.addColumn("Fecha de salida");//14
        modeloTabla.addColumn("Importe total");//15
        modeloTabla.addColumn("Usuario");//16
        jTReservas.setModel(modeloTabla);
    }

    private void cargarTabla(entidades.Reserva res) {
        modeloTabla.addRow(new Object[]{
            res.getIdReserva(),
            res.getIdHabitacion().getNumHabitacion(),
            res.getIdHabitacion().getPiso(),
            res.getIdHabitacion().isEstado(),
            res.getIdHuesped().getNombre(),
            res.getIdHuesped().getApellido(),
            res.getIdHuesped().getTipoDocumento(),
            res.getIdHuesped().getNumeroDocumento(),
            res.getIdHabitacion().getIdTipoHabitacion().getCategoria(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantCamas(),
            res.getIdHabitacion().getIdTipoHabitacion().getTipoCama(),
            res.getIdHabitacion().getIdTipoHabitacion().getPrecio(),
            res.getFechaEntrada(),
            res.getFechaSalida(),
            res.getImporteTotal(),
            res.getIdUsuarios().getIdUsuario(),
        });
    }

      private void llenarTabla() {

        for (Reserva r : resd.listarReserva()) {
            cargarTabla(r);
     }

    }
      
    public void listaRegistros() {
        int registro = 0;
        for (entidades.Reserva x : resd.listarReserva()) {
            cargarTabla(x);
            registro++;
        }
        jTnroRegistro.setText("Total de registros: " + registro);

    }

    private void borrarFilas() {

        int filas = jTReservas.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modeloTabla.removeRow(filas);
        }
    }
}
