/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ReservaData;
import accesoADatos.UsuariosData;
import entidades.Huesped;
import entidades.Reserva;
import entidades.Usuarios;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.table.DefaultTableModel;
import static vistas.VistaReserva.jDCfechaEntrada;
import static vistas.VistaReserva.jDCfechaSalida;
import static vistas.VistaReserva.jTAdmin;
import static vistas.VistaReserva.jTCantPersonas;
import static vistas.VistaReserva.jTHabitacion;
import static vistas.VistaReserva.jTHusped;
import static vistas.VistaReserva.jTImporte;
import static vistas.VistaReserva.jTablareservas;

/**
 *
 * @author 54911
 */
public class ListaReservas extends javax.swing.JInternalFrame {
public ReservaData resd= new ReservaData();
public Huesped h= new Huesped();
public UsuariosData user= new UsuariosData();
Usuarios usuario;
LocalDate fecha1 ,fecha2;
private DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    /**
     * Creates new form ListaReservas
     */
    public ListaReservas() {
        initComponents();
        armarCabecera();
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTReservas = new javax.swing.JTable();
        jTnroRegistro = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Listado Reservas");

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jTextbuscar.setBackground(new java.awt.Color(255, 204, 153));
        jTextbuscar.setText("Busca por nombre");
        jTextbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextbuscarFocusLost(evt);
            }
        });
        jTextbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextbuscarKeyReleased(evt);
            }
        });

        jTReservas.setBackground(new java.awt.Color(255, 204, 153));
        jTReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTReservas);

        jTnroRegistro.setBackground(new java.awt.Color(255, 204, 153));
        jTnroRegistro.setText("Total de registros:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTnroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTnroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(580, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 464, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextbuscarFocusGained
        jTextbuscar.setText("");
    }//GEN-LAST:event_jTextbuscarFocusGained

    private void jTextbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextbuscarFocusLost
        jTextbuscar.setText("Busca por numero de documento");
    }//GEN-LAST:event_jTextbuscarFocusLost

    private void jTextbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextbuscarKeyReleased
        borrarFilas();
        for (Reserva res : resd.listarReserva()) {
//            String numDocHuesped = h.getNumeroDocumento();
//            numDocHuesped=null;
//            if (numDocHuesped!=null && numDocHuesped.startsWith(jTextbuscar.getText())) {
//            cargarTabla(res); 
        if(res.getIdHuesped().getNumeroDocumento().startsWith(jTextbuscar.getText())){
            modeloTabla.addRow(new Object[]{
            res.getIdReserva(),
            res.getIdHabitacion().getNumHabitacion(),
            res.getIdHabitacion().getPiso(),
            res.getIdHabitacion().isEstado(),
            res.getIdHuesped().getNombre(),
            res.getIdHuesped().getApellido(),
            res.getIdHuesped().getTipoDocumento(),
            res.getIdHuesped().getNumeroDocumento(),
            res.getIdHabitacion().getIdTipoHabitacion().getCategoria(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantCamas(),
            res.getIdHabitacion().getIdTipoHabitacion().getTipoCama(),
            res.getIdHabitacion().getIdTipoHabitacion().getPrecio(),
            res.getFechaEntrada(),
            res.getFechaSalida(),
            res.getImporteTotal(),
            res.getIdUsuarios(),
                });
    }
            
        }   
    }//GEN-LAST:event_jTextbuscarKeyReleased
  

    private void jTReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTReservasMouseClicked
        if (evt.getClickCount() == 2){

            int fila = jTReservas.getSelectedRow();

            if (fila != -1) {
//                    String fechaE =jTReservas.getValueAt(fila, 13).toString();
//                    String fechaS =jTReservas.getValueAt(fila, 14).toString();
//                    java.util.Date f =forma.parse(fechaE);
//                    java.util.Date s = forma.parse(fechaS);
//                    jDCfechaEntrada.setDate(f);
//                    jDCfechaSalida.setDate(s);
//                    jTCantPersonas.setText(jTReservas.getValueAt(fila, 5).toString());
//                    jTHabitacion.setText(jTReservas.getValueAt(fila, 0).toString());
//                    jTHusped.setText(jTReservas.getValueAt(fila, 1).toString() + jTReservas.getValueAt(fila, 2).toString());
//                    jTImporte.setText(jTReservas.getValueAt(fila, 8).toString());                    
//                    Usuarios us = user.obtenerUsuarioId(Integer.parseInt(jTReservas.getValueAt(fila, 9).toString()));
//                    jTAdmin.setText(us.getNombre()+", "+us.getCargo());

            int nunres=(Integer)jTReservas.getValueAt(fila,0);
            int numhab=(Integer)jTReservas.getValueAt(fila,1);
            int numpiso=(Integer)jTReservas.getValueAt(fila,2);
            boolean estado=(Boolean)jTReservas.getValueAt(fila,3);
            String nomhues=(String)jTReservas.getValueAt(fila,4);
            String apelhues=(String)jTReservas.getValueAt(fila,5);
            String tipdoc=(String)jTReservas.getValueAt(fila,6);
            String numdoc=(String)jTReservas.getValueAt(fila,7);
            String categ=(String)jTReservas.getValueAt(fila,8);
            int cantpers=(Integer)jTReservas.getValueAt(fila,9);
            int cantcamas=(Integer)jTReservas.getValueAt(fila,10);
            String tipocama=(String)jTReservas.getValueAt(fila,11);
            double precio=(Double)jTReservas.getValueAt(fila,12);
            LocalDate FE=(LocalDate)jTReservas.getValueAt(fila,13);
            LocalDate FS=(LocalDate)jTReservas.getValueAt(fila,14);
            double imptot=(Double)jTReservas.getValueAt(fila,15);
            int iDusu=(Integer)jTReservas.getValueAt(fila,16);

            
            }
            dispose();
                    }
    }//GEN-LAST:event_jTReservasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTReservas;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTextField jTnroRegistro;
    // End of variables declaration//GEN-END:variables

 private void armarCabecera() {
        modeloTabla.addColumn("IdReserva");//0
        modeloTabla.addColumn("NºHabitación ");//1
        modeloTabla.addColumn("Piso");//2
        modeloTabla.addColumn("Estado");//3
        modeloTabla.addColumn("Nombre Huesped");//4
        modeloTabla.addColumn("Apellido Huesped");//5
        modeloTabla.addColumn("Tipo de Documento");//6
        modeloTabla.addColumn("Numero de Documento");//7
        modeloTabla.addColumn("Categoría");//8
        modeloTabla.addColumn("Cant.Personas");//9
        modeloTabla.addColumn("Cant.Camas");//10
        modeloTabla.addColumn("Tipo de Camas");//11
        modeloTabla.addColumn("Precio");//12
        modeloTabla.addColumn("Fecha entrada");//13
        modeloTabla.addColumn("Fecha de salida");//14
        modeloTabla.addColumn("Importe total");//15
        modeloTabla.addColumn("Usuario");//16
        jTReservas.setModel(modeloTabla);
    }

    private void cargarTabla(entidades.Reserva res) {
        modeloTabla.addRow(new Object[]{
            res.getIdReserva(),
            res.getIdHabitacion().getNumHabitacion(),
            res.getIdHabitacion().getPiso(),
            res.getIdHabitacion().isEstado(),
            res.getIdHuesped().getNombre(),
            res.getIdHuesped().getApellido(),
            res.getIdHuesped().getTipoDocumento(),
            res.getIdHuesped().getNumeroDocumento(),
            res.getIdHabitacion().getIdTipoHabitacion().getCategoria(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
            res.getIdHabitacion().getIdTipoHabitacion().getCantCamas(),
            res.getIdHabitacion().getIdTipoHabitacion().getTipoCama(),
            res.getIdHabitacion().getIdTipoHabitacion().getPrecio(),
            res.getFechaEntrada(),
            res.getFechaSalida(),
            res.getImporteTotal(),
            res.getIdUsuarios(),
        });
    }

      private void llenarTabla() {

        for (Reserva r : resd.listarReserva()) {
            cargarTabla(r);
        }

    }
      
    public void listaRegistros() {
        int registro = 0;
        for (entidades.Reserva x : resd.listarReserva()) {
            cargarTabla(x);
            registro++;
        }
        jTnroRegistro.setText("Total de registros: " + registro);

    }

    private void borrarFilas() {

        int filas = jTReservas.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modeloTabla.removeRow(filas);
        }
    }
}
