/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.HabitacionData;
import entidades.Habitacion;
import entidades.Reserva;
import entidades.TipoHabitacion;
import entidades.Usuarios;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vistas.VistaReserva.jDCfechaEntrada;
import static vistas.VistaReserva.jDCfechaSalida;
import static vistas.VistaReserva.jTAdmin;

/**
 *
 * @author fernandoalvarez
 */
public class listaHabitacionReserva extends javax.swing.JInternalFrame {
HabitacionData habitacion = new HabitacionData();
Usuarios user;
LocalDate fecha1 ,fecha2;
private DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    /**
     * Creates new form listaHabitacionreserva
     */
    public listaHabitacionReserva(Usuarios u) {
        this.user = u;
        initComponents();
        armarCabecera();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHabitacion = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(741, 506));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(151, 60, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Habitaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextBuscar.setBackground(new java.awt.Color(151, 60, 0));
        jTextBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jTextBuscar.setText("Busca por n° de Habitacion");
        jTextBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextBuscarFocusGained(evt);
            }
        });
        jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBuscarKeyReleased(evt);
            }
        });

        jTableHabitacion.setBackground(new java.awt.Color(151, 60, 0));
        jTableHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        jTableHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHabitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHabitacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 740, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHabitacionMouseClicked
        if (evt.getClickCount() == 2) {

            int fila = jTableHabitacion.getSelectedRow();

            if (fila != -1) {
                VistaReserva.jTHabitacion.setText(jTableHabitacion.getValueAt(fila, 0).toString());
                //calcula los dias y los multiplica por el precio de la habitacion
                double n = (Double.parseDouble(jTableHabitacion.getValueAt(fila, 7).toString()) * ChronoUnit.DAYS.between(fecha1, fecha2));
                VistaReserva.jTImporte.setText(n + "");
                jTAdmin.setText(user.getNombre() + " , " + user.getCargo());
            }
            dispose();
        }
    }//GEN-LAST:event_jTableHabitacionMouseClicked

    private void jTextBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextBuscarFocusGained
       jTextBuscar.setText("");
    }//GEN-LAST:event_jTextBuscarFocusGained

    private void jTextBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyReleased
        borrarFilas();
        fecha1 = VistaReserva.jDCfechaEntrada.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        fecha2 = VistaReserva.jDCfechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int personas = Integer.parseInt(VistaReserva.jTCantPersonas.getText());

        for (Habitacion hab : habitacion.listarReserva_X_fechasYcantDePersonas(fecha1, fecha2, personas)) {
            if (Integer.toString(hab.getNumHabitacion()).startsWith(jTextBuscar.getText())) {
                
                modeloTabla.addRow(new Object[]{
                    hab.getNumHabitacion(),
                    hab.getPiso(),
                    hab.isEstado(),
                    hab.getIdTipoHabitacion().getCategoria(),
                    hab.getIdTipoHabitacion().getCantPersonas(),
                    hab.getIdTipoHabitacion().getCantCamas(),
                    hab.getIdTipoHabitacion().getTipoCama(),
                    hab.getIdTipoHabitacion().getPrecio(),
                });
            }
        }
    }//GEN-LAST:event_jTextBuscarKeyReleased
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableHabitacion;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
  
    private void armarCabecera() {
        modeloTabla.addColumn("NºHabitación ");
        modeloTabla.addColumn("Piso");
        modeloTabla.addColumn("Estado");
        modeloTabla.addColumn("Categoría");
        modeloTabla.addColumn("Cant.Personas");
        modeloTabla.addColumn("Cant.Camas");
        modeloTabla.addColumn("Tipo de Camas");
        modeloTabla.addColumn("Precio");
        jTableHabitacion.setModel(modeloTabla);
    }

private void cargarTabla(Habitacion hab) {
        modeloTabla.addRow(new Object[]{
            hab.getNumHabitacion(),
            hab.getPiso(),
            hab.isEstado(),
            hab.getIdTipoHabitacion().getCategoria(),
            hab.getIdTipoHabitacion().getCantPersonas(),
            hab.getIdTipoHabitacion().getCantCamas(),
            hab.getIdTipoHabitacion().getTipoCama(),
            hab.getIdTipoHabitacion().getPrecio()
        });
    }

    private void llenarTabla() {
        fecha1 = VistaReserva.jDCfechaEntrada.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        fecha2 = VistaReserva.jDCfechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int personas = Integer.parseInt(VistaReserva.jTCantPersonas.getText());

        for (Habitacion hab : habitacion.listarReserva_X_fechasYcantDePersonas(fecha1, fecha2, personas)) {
            cargarTabla(hab);
        }
    }
     private void borrarFilas() {

        int filas = jTableHabitacion.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modeloTabla.removeRow(filas);
        }
    }
}