/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ReservaData;
import entidades.Reserva;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class VistaReserva extends javax.swing.JInternalFrame {
    ReservaData reserva = new ReservaData();
    public static int numero;
    private DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };    

    /**
     * Creates new form VistaReserva
     */
    public VistaReserva() {
        initComponents();    
        armarCabecera();
        camposApagados();
        listaRegistros();  
   
        jDCfechaEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {

                if (jDCfechaEntrada.getDate() == null) {                    
                    jDCfechaEntrada.setMinSelectableDate(new Date());
                    
                } else if ("date".equals(evt.getPropertyName())) {//captura el evento donde cambio la fecha

                    java.util.Date fechaActual = (java.util.Date) evt.getNewValue();
                    LocalDate fsalida = fechaActual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate().plusDays(1);
                    java.util.Date fechanueva = Date.from(fsalida.atStartOfDay(ZoneId.systemDefault()).toInstant());
                    jDCfechaSalida.setMinSelectableDate(fechanueva);

                }
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelRegistroReserva = new javax.swing.JPanel();
        jTHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBBuscarTipoH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTHusped = new javax.swing.JTextField();
        jBbuscarHuesped = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCantPersonas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTImporte = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDCfechaEntrada = new com.toedter.calendar.JDateChooser();
        jDCfechaSalida = new com.toedter.calendar.JDateChooser();
        jPanelListadoRegistroReserva = new javax.swing.JPanel();
        jTBuscaReservas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablareservas = new javax.swing.JTable();
        jBConsumos = new javax.swing.JButton();
        jBpago = new javax.swing.JButton();
        jTTotalRegistros = new javax.swing.JTextField();
        jBsalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Registro de reservas");

        jPanelRegistroReserva.setBackground(new java.awt.Color(255, 204, 153));

        jTHabitacion.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Habitacion: ");

        jBBuscarTipoH.setBackground(new java.awt.Color(255, 204, 153));
        jBBuscarTipoH.setText("buscar tipo hab");
        jBBuscarTipoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarTipoHActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Huesped:");

        jTHusped.setBackground(new java.awt.Color(255, 204, 153));
        jTHusped.setText("Obligatorio");

        jBbuscarHuesped.setBackground(new java.awt.Color(255, 204, 153));
        jBbuscarHuesped.setText("buscar H");
        jBbuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarHuespedActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Administrador:");

        jTAdmin.setBackground(new java.awt.Color(255, 204, 153));

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Cantidad Personas:");

        jTCantPersonas.setBackground(new java.awt.Color(255, 204, 153));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Importe:");

        jTImporte.setBackground(new java.awt.Color(255, 204, 153));

        jBCancelar.setBackground(new java.awt.Color(255, 204, 153));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBNuevo.setBackground(new java.awt.Color(255, 204, 153));
        jBNuevo.setText("Nuevo");

        jBGuardar.setBackground(new java.awt.Color(255, 204, 153));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fecha de Entrada:");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fecha de Salida:");

        javax.swing.GroupLayout jPanelRegistroReservaLayout = new javax.swing.GroupLayout(jPanelRegistroReserva);
        jPanelRegistroReserva.setLayout(jPanelRegistroReservaLayout);
        jPanelRegistroReservaLayout.setHorizontalGroup(
            jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(39, 39, 39))
            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(70, 70, 70)
                                .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jBNuevo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBGuardar)
                                    .addComponent(jTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jBBuscarTipoH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTHusped, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBbuscarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDCfechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDCfechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanelRegistroReservaLayout.setVerticalGroup(
            jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDCfechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscarTipoH)
                    .addComponent(jTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTHusped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscarHuesped))
                .addGap(64, 64, 64)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar)
                    .addComponent(jBNuevo))
                .addGap(15, 15, 15))
        );

        jPanelListadoRegistroReserva.setBackground(new java.awt.Color(255, 204, 153));

        jTBuscaReservas.setBackground(new java.awt.Color(255, 204, 153));
        jTBuscaReservas.setText("Busca tu reserva");

        jTablareservas.setBackground(new java.awt.Color(255, 204, 153));
        jTablareservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablareservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablareservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablareservas);

        jBConsumos.setBackground(new java.awt.Color(255, 204, 153));
        jBConsumos.setText("Consumos");

        jBpago.setBackground(new java.awt.Color(255, 204, 153));
        jBpago.setText("Realizar Pago");

        jTTotalRegistros.setBackground(new java.awt.Color(255, 204, 153));
        jTTotalRegistros.setText("Total de registros:");

        jBsalir.setBackground(new java.awt.Color(255, 204, 153));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setText("Cancelar Reserva");

        javax.swing.GroupLayout jPanelListadoRegistroReservaLayout = new javax.swing.GroupLayout(jPanelListadoRegistroReserva);
        jPanelListadoRegistroReserva.setLayout(jPanelListadoRegistroReservaLayout);
        jPanelListadoRegistroReservaLayout.setHorizontalGroup(
            jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBConsumos)
                .addGap(18, 18, 18)
                .addComponent(jBpago)
                .addGap(144, 144, 144)
                .addComponent(jTTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                        .addComponent(jTBuscaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalir)))
                .addGap(28, 28, 28))
        );
        jPanelListadoRegistroReservaLayout.setVerticalGroup(
            jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalir)
                    .addComponent(jButton1)
                    .addComponent(jTBuscaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsumos)
                    .addComponent(jBpago)
                    .addComponent(jTTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel9.setText("Listado de Reservas...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(196, 196, 196)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListadoRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListadoRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
          dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBbuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarHuespedActionPerformed
        listaHuespedes huesped = new listaHuespedes();
        Menu.escritorio.add(huesped);
        huesped.moveToFront();
        huesped.setVisible(true);       
    }//GEN-LAST:event_jBbuscarHuespedActionPerformed

    private void jBBuscarTipoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarTipoHActionPerformed
        if (habilitaLista()){
        listaHabitacionReserva reserva = new listaHabitacionReserva();
        Menu.escritorio.add(reserva);
        reserva.moveToFront();
        reserva.setVisible(true);
        }else{
         JOptionPane.showMessageDialog(null, "Complete los campos de fechas de ingreso, fecha de salida y cantidad de personas ");
         jTHabitacion.setText("");
        }
    }//GEN-LAST:event_jBBuscarTipoHActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if ((habilitaLista()) && (!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "se Habilita para generar un registro");
            //buscar huesped con el dni de numero para traer al huesped y registrarlo en reservas
            //hacer lo mismo con la habitacion
            //hacer lo mismo con el usuario
            
        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos para poder generar un registro ");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jTHabitacion.setText("");
        jTHusped.setText("");
        jDCfechaEntrada.setDate(null);
        jDCfechaSalida.setDate(null);
        jTCantPersonas.setText("");
        jTImporte.setText("");
        jTAdmin.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTablareservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablareservasMouseClicked
  
         SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
        if (evt.getClickCount() == 2) {
 
            int fila = jTablareservas.getSelectedRow();

            if (fila != -1) {
                try {
                    String fechaE =jTablareservas.getValueAt(fila, 10).toString();
                    String fechaS =jTablareservas.getValueAt(fila, 11).toString();
                    java.util.Date f =forma.parse(fechaE);
                    java.util.Date s = forma.parse(fechaS);
                    jDCfechaEntrada.setDate(f);
                    jDCfechaSalida.setDate(s);
                    jTCantPersonas.setText(jTablareservas.getValueAt(fila, 7).toString());
                    jTHabitacion.setText(jTablareservas.getValueAt(fila, 0).toString());
                    jTHusped.setText(jTablareservas.getValueAt(fila, 3).toString() + jTablareservas.getValueAt(fila, 4).toString());
                    jTImporte.setText(jTablareservas.getValueAt(fila, 12).toString());
                    jTAdmin.setText("");
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null,"Se produjo un error en el ingreso de la fecha"+ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_jTablareservasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarTipoH;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConsumos;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBbuscarHuesped;
    private javax.swing.JButton jBpago;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCfechaEntrada;
    private com.toedter.calendar.JDateChooser jDCfechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelListadoRegistroReserva;
    private javax.swing.JPanel jPanelRegistroReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAdmin;
    private javax.swing.JTextField jTBuscaReservas;
    private javax.swing.JTextField jTCantPersonas;
    public static javax.swing.JTextField jTHabitacion;
    public static javax.swing.JTextField jTHusped;
    public static javax.swing.JTextField jTImporte;
    private javax.swing.JTextField jTTotalRegistros;
    private javax.swing.JTable jTablareservas;
    // End of variables declaration//GEN-END:variables
  public boolean habilitaLista() {
        boolean aux = false;
        
        if ((jDCfechaEntrada.getDate() != null)
                && (jDCfechaSalida.getDate() != null)
                && (!jTCantPersonas.getText().isEmpty())) {
            try{
            int cantp = Integer.parseInt(jTCantPersonas.getText());
            if (cantp < 0) {
                JOptionPane.showMessageDialog(null, "La cantidad de personas no puede ser menor que cero");
                jTCantPersonas.setText("");
                aux = false;
            }else{
             aux= true;
            }         
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Este campo acepta solo números");
                jTCantPersonas.setText("");
            }
        }
        return aux;
    }
      private void armarCabecera() {
        modeloTabla.addColumn("NºHabitación ");//0
        modeloTabla.addColumn("Piso");//1
        modeloTabla.addColumn("Estado");//2
        modeloTabla.addColumn("Nombre Huesped");//3
        modeloTabla.addColumn("Apellido Huesped");//4
        modeloTabla.addColumn("Tipo de Documento");//5
        modeloTabla.addColumn("Numero de Documento");//6
        modeloTabla.addColumn("Categoría");//7
        modeloTabla.addColumn("Cant.Personas");//8
        modeloTabla.addColumn("Cant.Camas");//9
        modeloTabla.addColumn("Tipo de Camas");//10
        modeloTabla.addColumn("Fecha entrada");//11
        modeloTabla.addColumn("Fecha de salida");//12
        modeloTabla.addColumn("Importe total");//13
        jTablareservas.setModel(modeloTabla);
    }

    private void cargarTabla(Reserva r) {
        modeloTabla.addRow(new Object[]{
           r.getIdHabitacion().getNumHabitacion(),
           r.getIdHabitacion().getPiso(),
           r.getIdHabitacion().isEstado(),
           r.getIdHuesped().getNombre(),
           r.getIdHuesped().getApellido(),
           r.getIdHuesped().getTipoDocumento(),
           r.getIdHuesped().getNumeroDocumento(),
           r.getIdHabitacion().getIdTipoHabitacion().getCategoria(),
           r.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
           r.getIdHabitacion().getIdTipoHabitacion().getCantCamas(),
           r.getIdHabitacion().getIdTipoHabitacion().getTipoCama(),
           r.getFechaEntrada(),
           r.getFechaSalida(),
           r.getImporteTotal()
        });
    }
     public void listaRegistros(){     
        for(Reserva res:reserva.listarReserva())
            cargarTabla(res);
     
    }
    public void camposApagados() {
        jTHabitacion.setEditable(false);
        jTHusped.setEditable(false);
        jTImporte.setEditable(false);
        jTAdmin.setEditable(false);
    }
  
  
  
  
  
  
  
}// fin class
