/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.HabitacionData;
import accesoADatos.HuespedData;
import accesoADatos.ReservaData;
import accesoADatos.UsuariosData;
import entidades.Habitacion;
import entidades.Huesped;
import entidades.ProductoServicio;
import entidades.Reserva;
import entidades.Usuarios;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class VistaReserva extends javax.swing.JInternalFrame {

    Usuarios usuario;
    public static ReservaData reserva = new ReservaData();
    HuespedData huesped = new HuespedData();
    HabitacionData habitacion = new HabitacionData();
    UsuariosData user = new UsuariosData();
    public static String numDniHuesped = "";
    public DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    /**
     * Creates new form VistaReserva
     */
    public VistaReserva(Usuarios u) {
        this.usuario = u;
        initComponents();
        armarCabecera();
        camposApagados();
        listaRegistros();

          jDCfechaEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {

                if (jDCfechaEntrada.getDate() == null) {
                    jDCfechaEntrada.setMinSelectableDate(new Date());
                    jDCfechaSalida.setEnabled(false);
                    

                } else if ("date".equals(evt.getPropertyName())) {//captura el evento donde cambio la fecha

                    java.util.Date fechaActual = (java.util.Date) evt.getNewValue();
                    LocalDate fsalida = fechaActual.toInstant().atZone(ZoneId.systemDefault()).toLocalDate().plusDays(1);
                    java.util.Date fechanueva = Date.from(fsalida.atStartOfDay(ZoneId.systemDefault()).toInstant());
                    jDCfechaSalida.setEnabled(true);
                    jDCfechaSalida.setDate(null);
                    jDCfechaSalida.setMinSelectableDate(fechanueva);
                    jTHabitacion.setText("");
                    jTImporte.setText("");
                }
            }
        }
        );
          jDCfechaSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {

                if (jDCfechaSalida.getDate() == null){
                    return;
                } else if ("date".equals(evt.getPropertyName())) {//captura el evento donde cambio la fecha

                    jTHabitacion.setText("");
                    jTImporte.setText("");
                }
            }
        }
        );    
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelRegistroReserva = new javax.swing.JPanel();
        jTHabitacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBBuscarTipoH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTHusped = new javax.swing.JTextField();
        jBbuscarHuesped = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTCantPersonas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTImporte = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDCfechaEntrada = new com.toedter.calendar.JDateChooser();
        jDCfechaSalida = new com.toedter.calendar.JDateChooser();
        jPanelListadoRegistroReserva = new javax.swing.JPanel();
        jTBuscaReservas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablareservas = new javax.swing.JTable();
        jBConsumos = new javax.swing.JButton();
        jBpago = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jBCheckIn = new javax.swing.JButton();
        jBcancelarReserva = new javax.swing.JButton();
        jTTotalRegistros = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Registro de reservas");

        jPanelRegistroReserva.setBackground(new java.awt.Color(255, 204, 153));

        jTHabitacion.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Habitacion: ");

        jBBuscarTipoH.setBackground(new java.awt.Color(255, 204, 153));
        jBBuscarTipoH.setText("buscar tipo hab");
        jBBuscarTipoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarTipoHActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Huesped:");

        jTHusped.setBackground(new java.awt.Color(255, 204, 153));

        jBbuscarHuesped.setBackground(new java.awt.Color(255, 204, 153));
        jBbuscarHuesped.setText("buscar H");
        jBbuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarHuespedActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Administrador:");

        jTAdmin.setBackground(new java.awt.Color(255, 204, 153));

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Cantidad Personas:");

        jTCantPersonas.setBackground(new java.awt.Color(255, 204, 153));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Importe:");

        jTImporte.setBackground(new java.awt.Color(255, 204, 153));

        jBCancelar.setBackground(new java.awt.Color(255, 204, 153));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(255, 204, 153));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fecha de Entrada:");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fecha de Salida:");

        javax.swing.GroupLayout jPanelRegistroReservaLayout = new javax.swing.GroupLayout(jPanelRegistroReserva);
        jPanelRegistroReserva.setLayout(jPanelRegistroReservaLayout);
        jPanelRegistroReservaLayout.setHorizontalGroup(
            jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(39, 39, 39))
            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(70, 70, 70)
                                .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBGuardar)
                                    .addComponent(jTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addComponent(jTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jBBuscarTipoH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTHusped, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBbuscarHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDCfechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDCfechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanelRegistroReservaLayout.setVerticalGroup(
            jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroReservaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDCfechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDCfechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscarTipoH)
                    .addComponent(jTHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTHusped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscarHuesped))
                .addGap(64, 64, 64)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanelRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addGap(15, 15, 15))
        );

        jPanelListadoRegistroReserva.setBackground(new java.awt.Color(255, 204, 153));

        jTBuscaReservas.setBackground(new java.awt.Color(255, 204, 153));
        jTBuscaReservas.setForeground(new java.awt.Color(128, 128, 128));
        jTBuscaReservas.setText("Busca reserva por Nombre, DNI o Nª habitación");
        jTBuscaReservas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTBuscaReservasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTBuscaReservasFocusLost(evt);
            }
        });
        jTBuscaReservas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBuscaReservasKeyReleased(evt);
            }
        });

        jTablareservas.setBackground(new java.awt.Color(255, 204, 153));
        jTablareservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablareservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablareservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablareservas);

        jBConsumos.setBackground(new java.awt.Color(255, 204, 153));
        jBConsumos.setText("Consumos");
        jBConsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsumosActionPerformed(evt);
            }
        });

        jBpago.setBackground(new java.awt.Color(255, 204, 153));
        jBpago.setText("Realizar Pago");
        jBpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpagoActionPerformed(evt);
            }
        });

        jBsalir.setBackground(new java.awt.Color(255, 204, 153));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jBCheckIn.setBackground(new java.awt.Color(255, 204, 153));
        jBCheckIn.setText("CheckIn");
        jBCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCheckInActionPerformed(evt);
            }
        });

        jBcancelarReserva.setBackground(new java.awt.Color(255, 204, 153));
        jBcancelarReserva.setText("Cancelar Reserva");
        jBcancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarReservaActionPerformed(evt);
            }
        });

        jTTotalRegistros.setBackground(new java.awt.Color(255, 204, 153));
        jTTotalRegistros.setText("Total de registros:");

        javax.swing.GroupLayout jPanelListadoRegistroReservaLayout = new javax.swing.GroupLayout(jPanelListadoRegistroReserva);
        jPanelListadoRegistroReserva.setLayout(jPanelListadoRegistroReservaLayout);
        jPanelListadoRegistroReservaLayout.setHorizontalGroup(
            jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jBConsumos)
                .addGap(18, 18, 18)
                .addComponent(jBpago)
                .addGap(18, 18, 18)
                .addComponent(jBCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                        .addComponent(jTBuscaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jBcancelarReserva)
                        .addGap(41, 41, 41)
                        .addComponent(jBsalir)))
                .addGap(28, 28, 28))
        );
        jPanelListadoRegistroReservaLayout.setVerticalGroup(
            jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalir)
                    .addComponent(jTBuscaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelarReserva))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanelListadoRegistroReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBConsumos)
                            .addComponent(jBpago)
                            .addComponent(jBCheckIn))
                        .addGap(74, 74, 74))
                    .addGroup(jPanelListadoRegistroReservaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel9.setText("Listado de Reservas...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(196, 196, 196)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListadoRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListadoRegistroReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBbuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarHuespedActionPerformed
        listaHuespedes huesped = new listaHuespedes();
        Menu.escritorio.add(huesped);
        huesped.moveToFront();
        huesped.setVisible(true);
    }//GEN-LAST:event_jBbuscarHuespedActionPerformed

    private void jBBuscarTipoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarTipoHActionPerformed
        if (habilitaLista()) {
            listaHabitacionReserva reserva = new listaHabitacionReserva(usuario);
            Menu.escritorio.add(reserva);
            reserva.moveToFront();
            reserva.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Complete los campos de fechas de ingreso, fecha de salida y cantidad de personas ");
            jTHabitacion.setText("");
        }
    }//GEN-LAST:event_jBBuscarTipoHActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
     
      if ((habilitaLista()) && (!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty())) {
            
            Huesped hues = huesped.buscarHuespedPorDni(numDniHuesped);
            Habitacion hab = habitacion.buscarHabitacion(Integer.parseInt(jTHabitacion.getText()));
            hab.setEstado(false);
            habitacion.modificarHabitacion(hab);// la habitacion esta ocupada
            
            LocalDate entrada = jDCfechaEntrada.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate salida = jDCfechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            double importe = Double.parseDouble(jTImporte.getText().toString());
            int canPersonas = Integer.parseInt(jTCantPersonas.getText().toString());
            
            Reserva res = new Reserva(hab,hues,usuario,entrada,salida,importe,canPersonas,true);
            reserva.crearReserva(res);
            JOptionPane.showMessageDialog(null, "Se realizó una reserva ");
            limpiaCampos();
            listaRegistros();
            jBGuardar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos para poder generar un registro ");
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        limpiaCampos();
        jBGuardar.setEnabled(true);
        jTablareservas.clearSelection();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTablareservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablareservasMouseClicked

        SimpleDateFormat forma = new SimpleDateFormat("yyyy-MM-dd");
        if (evt.getClickCount() == 2) {
            
            jBGuardar.setEnabled(false);
            int fila = jTablareservas.getSelectedRow();
            
            if (fila != -1) {
                try {
                    String fechaE =jTablareservas.getValueAt(fila, 5).toString();
                    String fechaS =jTablareservas.getValueAt(fila, 6).toString();
                    java.util.Date f =forma.parse(fechaE);
                    java.util.Date s = forma.parse(fechaS);
                    jDCfechaEntrada.setDate(f);
                    jDCfechaSalida.setDate(s);
                    jTCantPersonas.setText(jTablareservas.getValueAt(fila, 8).toString());
                    jTHabitacion.setText(jTablareservas.getValueAt(fila, 7).toString());
                    jTHusped.setText(jTablareservas.getValueAt(fila, 1).toString() + jTablareservas.getValueAt(fila, 2).toString());
                    jTImporte.setText(jTablareservas.getValueAt(fila, 9).toString());                    
                    Usuarios us = user.obtenerUsuarioId(Integer.parseInt(jTablareservas.getValueAt(fila, 10).toString()));
                    jTAdmin.setText(us.getNombre()+", "+us.getCargo());
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null,"Se produjo un error en el ingreso de la fecha"+ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_jTablareservasMouseClicked

    private void jBConsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsumosActionPerformed
        if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "La tabla esta vacía");

        } else {
            int fila = jTablareservas.getSelectedRow();
            if ((fila != -1)&&((habilitaLista()) && (!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty()))) {
                if (jTablareservas.getValueAt(fila,11)!= null){
                Consumos.idReserva = Integer.parseInt(jTablareservas.getValueAt(fila, 0).toString());
                Consumos consu = new Consumos();
                Menu.escritorio.add(consu);
                consu.moveToFront();
                consu.setVisible(true);   
                }else{
                JOptionPane.showMessageDialog(null, "La persona no se encuentra hospedada ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un registro con doble click para agregarle un consumo ");
            }
        }
    }//GEN-LAST:event_jBConsumosActionPerformed

    private void jBpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpagoActionPerformed
      if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "La tabla esta vacía");

        } else {
            int fila = jTablareservas.getSelectedRow();
           if ((fila != -1)&& (!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty())) {
                PagosView.idReserva = Integer.parseInt(jTablareservas.getValueAt(fila,0).toString());
                PagosView pago = new PagosView();
                Menu.escritorio.add(pago);
                pago.moveToFront();
                pago.setVisible(true);     
                
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un registro con doble click para realizar el pago");
            }
        }
         
    }//GEN-LAST:event_jBpagoActionPerformed

    private void jTBuscaReservasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTBuscaReservasFocusGained
        jTBuscaReservas.setText("");
    }//GEN-LAST:event_jTBuscaReservasFocusGained

    private void jTBuscaReservasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTBuscaReservasFocusLost
       jTBuscaReservas.setText("Busca reserva por Nombre, DNI o Nªde Reserva ");
    }//GEN-LAST:event_jTBuscaReservasFocusLost

    private void jTBuscaReservasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBuscaReservasKeyReleased
     borrarFilas();
        for (Reserva r : reserva.listarReserva()) {
            jTBuscaReservas.getText().toLowerCase();
            if ((r.getIdHuesped().getNombre().toLowerCase().startsWith(jTBuscaReservas.getText()))
                    || (r.getIdHuesped().getNumeroDocumento().startsWith(jTBuscaReservas.getText()))
                    || (String.valueOf(r.getIdReserva()).startsWith(jTBuscaReservas.getText()))) {

                modeloTabla.addRow(new Object[]{
                    r.getIdReserva(),
                    r.getIdHuesped().getNombre(),
                    r.getIdHuesped().getApellido(),
                    r.getIdHuesped().getTipoDocumento(),
                    r.getIdHuesped().getNumeroDocumento(),
                    r.getFechaEntrada(),
                    r.getFechaSalida(),
                    r.getIdHabitacion().getNumHabitacion(),
                    r.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
                    r.getImporteTotal(),
                    r.getIdUsuarios().getIdUsuario(),
                    r.getCheckIn()
                });
            }
        }
    }//GEN-LAST:event_jTBuscaReservasKeyReleased

    private void jBCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCheckInActionPerformed

        if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "La tabla esta vacía");

        } else {
            int fila = jTablareservas.getSelectedRow();
           
            
            if ((fila != -1) && (!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty())) {

                LocalDate hoy = LocalDate.now();
                LocalDate fechaE = (LocalDate) jTablareservas.getValueAt(fila, 5);
                int idreserva = Integer.parseInt(jTablareservas.getValueAt(fila, 0).toString());
                Reserva r = reserva.buscarReservaId(idreserva);

                if (r.getCheckIn() == null) {
                    if (hoy.equals(fechaE)) {
                        r.realizarCheckIn();
                        reserva.modificarCheckInReserva(idreserva, r.getCheckIn());
                    } else {
                        JOptionPane.showMessageDialog(null, "El CheckIn debe coincidir con la fecha de inicio de la Reserva ");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Este registro ya tiene un check-in registrado. No se puede realizar otro check-in en la misma reserva.");
                }
                limpiaCampos();             
                listaRegistros();
                jBGuardar.setEnabled(true);
 
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un registro con doble click ");
            }
        }
    }//GEN-LAST:event_jBCheckInActionPerformed

    private void jBcancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarReservaActionPerformed
       if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "La tabla esta vacía");

        } else {
            int fila = jTablareservas.getSelectedRow();
            if ((fila != -1)&&(!jTHabitacion.getText().isEmpty()) && (!jTHusped.getText().isEmpty())) {
                int idreserva = Integer.parseInt(jTablareservas.getValueAt(fila, 0).toString());
                Reserva r = reserva.buscarReservaId(idreserva);
                if (jTablareservas.getValueAt(fila, 11) == null) {
                    reserva.cancelarReserva(idreserva);
                    JOptionPane.showMessageDialog(null, "Reserva cancelada");
                } else {
                    JOptionPane.showMessageDialog(null, "Este registro ya tiene un check In, no se puede cancelar");
                }
                limpiaCampos();
                listaRegistros();
                jBGuardar.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un registro con doble click ");
            }
        }
    }//GEN-LAST:event_jBcancelarReservaActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarTipoH;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCheckIn;
    private javax.swing.JButton jBConsumos;
    public static javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBbuscarHuesped;
    private javax.swing.JButton jBcancelarReserva;
    private javax.swing.JButton jBpago;
    private javax.swing.JButton jBsalir;
    public static com.toedter.calendar.JDateChooser jDCfechaEntrada;
    public static com.toedter.calendar.JDateChooser jDCfechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelListadoRegistroReserva;
    private javax.swing.JPanel jPanelRegistroReserva;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTAdmin;
    private javax.swing.JTextField jTBuscaReservas;
    public static javax.swing.JTextField jTCantPersonas;
    public static javax.swing.JTextField jTHabitacion;
    public static javax.swing.JTextField jTHusped;
    public static javax.swing.JTextField jTImporte;
    public static javax.swing.JTextField jTTotalRegistros;
    public static javax.swing.JTable jTablareservas;
    // End of variables declaration//GEN-END:variables
  
    public boolean habilitaLista() {
        boolean aux = false;

        if ((jDCfechaEntrada.getDate() != null)
                && (jDCfechaSalida.getDate() != null)
                && (!jTCantPersonas.getText().isEmpty())) {
            try {
                int cantp = Integer.parseInt(jTCantPersonas.getText());
                if (cantp < 0) {
                    JOptionPane.showMessageDialog(null, "La cantidad de personas no puede ser menor que cero");
                    jTCantPersonas.setText("");
                    aux = false;
                } else {
                    aux = true;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Este campo acepta solo números");
                jTCantPersonas.setText("");
            }
        }
        return aux;
    }

    private void armarCabecera() {
        modeloTabla.addColumn("idReserva");//0
        modeloTabla.addColumn("Nombre Huesped");//1
        modeloTabla.addColumn("Apellido Huesped");//2
        modeloTabla.addColumn("Tipo de Documento");//3
        modeloTabla.addColumn("Numero de Documento");//4    
        modeloTabla.addColumn("Fecha entrada");//5
        modeloTabla.addColumn("Fecha de salida");//6
        modeloTabla.addColumn("NºHabitación ");//7
        modeloTabla.addColumn("Cant.Personas");//8
        modeloTabla.addColumn("Importe total");//9
        modeloTabla.addColumn("Usuario");//10
        modeloTabla.addColumn("CheckIn");//11

        jTablareservas.setModel(modeloTabla);
    }

    public static void cargarTabla(Reserva r) {
    DefaultTableModel modeloTabla = (DefaultTableModel) jTablareservas.getModel();    
           modeloTabla.addRow(new Object[]{
            r.getIdReserva(),
            r.getIdHuesped().getNombre(),
            r.getIdHuesped().getApellido(),
            r.getIdHuesped().getTipoDocumento(),
            r.getIdHuesped().getNumeroDocumento(),
            r.getFechaEntrada(),
            r.getFechaSalida(),
            r.getIdHabitacion().getNumHabitacion(),
            r.getIdHabitacion().getIdTipoHabitacion().getCantPersonas(),
            r.getImporteTotal(),
            r.getIdUsuarios().getIdUsuario(),
            r.getCheckIn()

        });
    }

    public static void listaRegistros() {
     DefaultTableModel modeloTabla = (DefaultTableModel) jTablareservas.getModel();
        limpia();
        int registro = 0;

        for (Reserva res : reserva.listarReserva()) {
            cargarTabla(res);
            registro++;
        }
        modeloTabla.fireTableDataChanged();
        jTTotalRegistros.setText("Total de registros: " + registro);
        jTablareservas.clearSelection();
        jTablareservas.repaint();
    }

    public void camposApagados() {
        jTHabitacion.setEditable(false);
        jTHusped.setEditable(false);
        jTImporte.setEditable(false);
        jTAdmin.setEditable(false);
    }

    public static void limpiaCampos() {
        jTHabitacion.setText("");
        jTHusped.setText("");
        jDCfechaEntrada.setDate(null);
        jDCfechaSalida.setDate(null);
        jTCantPersonas.setText("");
        jTImporte.setText("");
        jTAdmin.setText("");

    }
     private void borrarFilas() {

        int filas = jTablareservas.getRowCount() - 1;
        for (; filas >= 0; filas--) {
            modeloTabla.removeRow(filas);
        }
    }
     
    public static void limpia() {
    DefaultTableModel modeloTabla = (DefaultTableModel) jTablareservas.getModel();
    int fila = modeloTabla.getRowCount();
    
    for (int i = fila - 1; i >= 0; i--) {
        modeloTabla.removeRow(i);
    }
    
    // Notificar a la vista que se han realizado cambios en el modelo de la tabla
    modeloTabla.fireTableDataChanged();
}

    
    
    
}// fin class
